spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cabinet?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456

logging:
  level:
    com.suzhou: debug